ALTER TABLE "containers"
  ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'fraction',
  ADD COLUMN IF NOT EXISTS "share" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "packWeight" DOUBLE PRECISION NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "weightConfirmed" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "balance" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "containers"
  ALTER COLUMN "category" SET DEFAULT 'fraction',
  ALTER COLUMN "weight" SET DEFAULT 0,
  ALTER COLUMN "quantity" SET DEFAULT 1;
